name: Build commit

on:
  push:
    branches-ignore:
      - "**.**.**"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 20
          cache: gradle

      - name: Build with Gradle
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > $GITHUB_WORKSPACE/key.jks
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/key.jks -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Rename demo APK
        run: mv demo/build/outputs/apk/release/demo-release.apk toptoast_demo.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: toptoast_demo
          path: toptoast_demo.apk