name: Release alpha

on:
  push:
    tags:
      - "**-alpha**"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 20
          cache: gradle

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Sign demo APK
        id: sign_apk
        uses: ilharp/sign-android-release@v1
        with:
          releaseDir: ./demo/build/outputs/apk/release/
          signingKey: ${{ secrets.KEYSTORE_BASE64 }}
          keyAlias: ${{ secrets.KEYSTORE_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Rename signed APK
        run: mv ${{steps.sign_apk.outputs.signedFile}} toptoast_demo.apk

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: true
          files: |
            toptoast_demo.apk

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_PACKAGES_URL: https://maven.pkg.github.com/${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}